[package]
name = "magnum_opus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.0"
bytes = "1.10.0"
regex = "1.11.0"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
zip = "2.2.3"
